spring.application.name=Auth-Service
server.port = 8080


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecommerce_DB
spring.datasource.username=postgres
spring.datasource.password=130805@Tvr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =============================================
# JWT Configuration
# =============================================
jwt.secret=dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9ySldUQXV0aFNlcnZpY2VJbnRlbGxpQ2FydFBsYXRmb3Jt
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
jwt.issuer=IntelliCart-Auth-Service
jwt.audience=IntelliCart-Platform



# =============================================
# Logging
# =============================================
logging.level.com.example.Auth_Service=DEBUG
logging.level.org.springframework.security=WARN