name: Backend CI

on:
  push:
    paths:
      - 'API-Gateway/**'
      - 'Auth-Service/**'
      - 'Cart-Service/**'
      - 'Inventory-Service/**'
      - 'Order-Service/**'
      - 'Product-Service/**'
      - 'Service-Registry/**'
      - 'User-Service/**'
  pull_request:
    paths:
      - 'API-Gateway/**'
      - 'Auth-Service/**'
      - 'Cart-Service/**'
      - 'Inventory-Service/**'
      - 'Order-Service/**'
      - 'Product-Service/**'
      - 'Service-Registry/**'
      - 'User-Service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'API-Gateway/API-Gateway',
          'Auth-Service/Auth-Service',
          'Cart-Service/Cart-Service',
          'Inventory-Service/Inventory-Service',
          'Order-Service/Order-Service',
          'Product-Service/Product-Service',
          'Service-Registry/Service-Registry',
          'User-Service/User-Service'
        ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Test with Maven
      run: mvn clean test
      working-directory: ${{ matrix.service }}
